include: package:flutter_lints/flutter.yaml

# analyzer:
#   errors:
#     prefer_const_constructors: info
#     prefer_const_literals_to_create_immutables: info
#     prefer_const_declarations: info
#     prefer_const_constructors_in_immutables: info

# linter:
#   rules:
#     - prefer_const_constructors
#     - prefer_const_literals_to_create_immutables
#     - prefer_const_declarations
#     - prefer_const_constructors_in_immutables